-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : jeu. 21 mars 2024 à 14:47
-- Version du serveur : 10.4.25-MariaDB
-- Version de PHP : 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `bd_mini_projet_yannick_david`
--

-- --------------------------------------------------------

--
-- Structure de la table `jeux`
--

CREATE TABLE `jeux` (
  `id_jeux` int(11) NOT NULL,
  `id_plateforme` int(11) NOT NULL,
  `nom` varchar(40) NOT NULL,
  `annee` date NOT NULL,
  `image` varchar(255) NOT NULL,
  `video` varchar(50) DEFAULT NULL,
  `description` text NOT NULL,
  `note` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `jeux`
--

INSERT INTO `jeux` (`id_jeux`, `id_plateforme`, `nom`, `annee`, `image`, `video`, `description`, `note`) VALUES
(1, 1, 'The Last of Us Remastered', '2014-07-30', 'https://img.seriebox.com/jeux/6/6985/jaquette_64_6985_1.jpg?id=498', 'https://www.youtube.com/watch?v=JdZtkxxueYg', 'Dans un monde post-pandémique hostile, Joel et Ellie, réunis par un concours de circonstances, doivent s\'entraider pour survivre à un violent périple à travers ce qui reste des États-Unis.', 95),
(2, 1, 'The Last of Us Part II', '2020-06-19', 'https://img.seriebox.com/jeux/13/13838/jaquette_64_13838_2.jpg?id=942', 'https://www.youtube.com/watch?v=vhII1qlcZ4E', 'Cinq ans plus tard…\r\n\r\nAprès un voyage mortel à travers des États-Unis post-pandémie, Ellie et Joel s’installent dans le Wyoming.\r\n\r\nLa vie dans une communauté prospère leur apporte une certaine stabilité, malgré la menace que représentent les infectés et les survivants désespérés.\r\n\r\nQuand un violent incident vient troubler cette paix, Ellie entame une longue et implacable quête de justice. Alors qu’elle traque les responsables, elle se trouve confrontée aux répercussions physiques et émotionnelles dévastatrices de ses actes.', 93),
(3, 1, 'Uncharted 4 A Thief\'s End', '2016-05-10', 'https://img.seriebox.com/jeux/6/6787/jaquette_64_6787_2.jpg?id=777\r\n\r\n', 'https://www.youtube.com/watch?v=hh5HV4iic1Y', 'Plusieurs années après sa dernière aventure, le chasseur de trésors à la retraite Nathan Drake se voit obligé de revenir dans le monde des voleurs.\r\nLe destin ne tarde pas à revenir au galop quand Sam, le frère présumé mort de Drake, refait surface pour lui demander de l\'aider à sauver sa vie et propose à Drake une aventure qu\'il ne peut refuser.\r\nCette fois, l\'enjeu est personnel et il embarque pour un voyage à travers le monde à la poursuite de la conspiration historique que cache un mythique trésor de pirates.', 93),
(4, 1, 'Horizon Zero Dawn', '2017-03-01', 'https://img.seriebox.com/jeux/10/10211/jaquette_64_10211_2.jpg', 'https://www.youtube.com/watch?v=wzx96gYA8ek', 'LA TERRE NE NOUS APPARTIENT PLUS\r\n\r\nDécouvrez la quête légendaire d\'Aloy, une jeune Nora, et dévoilez les mystères d\'un monde dominé par de redoutables machines.\r\n\r\nRejetée par sa tribu, la chasseuse combat pour découvrir son passé et son destin… et arrêter une catastrophe menaçant le futur.\r\n\r\nDéchaînez de puissantes attaques tactiques contre des machines uniques et des tribus rivales alors que vous explorez un monde rempli d\'animaux sauvages et de dangers.\r\n\r\nHorizon Zero Dawn™ est un jeu de rôle et d\'action très primé. La Complete Edition inclut la magnifique extension The Frozen Wilds, avec de nouveaux territoires, compétences, armes et machines.', 89),
(5, 1, 'God of War', '2018-04-24', 'https://img.seriebox.com/jeux/10/10069/jaquette_64_10069_2.jpg', 'https://www.youtube.com/watch?v=K0u_kAWLJOA', 'Vivant comme un homme loin de l’ombre des dieux, Kratos doit faire face à un monde inconnu, des menaces inattendues et une nouvelle chance d’être père. Avec son fils Atreus, il devra affronter le royaume de Midgard et ses dangers pour accomplir une quête des plus personnelles.', 94),
(6, 1, 'God of War Ragnarök', '2022-11-09', 'https://img.seriebox.com/jeux/21/21276/jaquette_64_21276_2.jpg', 'https://www.youtube.com/watch?v=0taDnGk3oK4', 'Rejoignez Kratos et Atreus dans leur voyage légendaire en quête de réponses avant le début du Ragnarök. Ensemble, père et fils devront prendre des risques tout au long de leur périple vers chacun des neuf royaumes.\r\n\r\nAu cœur de paysages mythologiques à couper le souffle, ils affronteront de terribles ennemis, des dieux nordiques aux bêtes sauvages, alors qu\'ils se préparent pour l\'affrontement de leur vie.\r\n\r\nArmé de ses fidèles armes de guerre, et notamment de la Hache Léviathan et des Lames du Chaos, Kratos va voir ses compétences guerrières mises à rude épreuve dans son combat pour protéger sa famille. Atreus et lui auront accès à une myriade de nouvelles capacités, laissant la possibilité à l\'expression et à la fluidité lors des combats de cette épopée épique.\r\n\r\nEt pendant ce temps, Asgard rassemble ses forces...', NULL),
(7, 1, 'Marvel\'s Spider-Man', '2018-09-07', 'https://img.seriebox.com/jeux/13/13579/jaquette_64_13579_1.jpg', 'https://www.youtube.com/watch?v=Uc7ffNjyxBM', 'SOYEZ PLUS FORT.\r\n\r\nExplorez un nouveau chapitre de l\'univers de Spider-Man avec un Peter Parker plus expérimenté.\r\n\r\nMettant en vedette l\'un des héros les plus emblématiques de la planète, le nouveau Spider-Man vous offre toutes les acrobaties, les improvisations et la voltige sur toile que vous attendez, tout en vous surprenant avec des éléments jamais vus dans un jeu Spider-Man.\r\n\r\nMaîtrisez l\'art du parkour dans des environnements interactifs uniques, faites face à de nouveaux combats et à des scènes d\'action dignes d\'un blockbuster. Découvrez Spider-Man comme vous ne l\'avez jamais vu !', 87),
(8, 1, 'Marvel\'s Spider-Man Miles Morales', '2020-11-12', 'https://img.seriebox.com/jeux/19/19288/jaquette_64_19288_1.jpg', 'https://www.youtube.com/watch?v=3Ywq3PIKAYo', 'Dans la dernière aventure de l\'univers Marvel’s Spider-Man, le jeune Miles Morales prend ses marques dans son nouveau foyer tout en marchant dans les pas de son mentor, Peter Parker, en tant que nouveau Spider-Man. Mais quand une lutte de pouvoir menace de détruire son nouveau foyer, le héros en devenir se rend compte qu\'un grand pouvoir implique de grandes responsabilités. Pour sauver New York, Mile doit enfiler la tenue de Spider-Man et lui faire honneur.', 84),
(9, 2, 'Marvel\'s Spider-Man Remastered', '2020-11-19', 'https://img.seriebox.com/jeux/19/19369/jaquette_84_19369_1.jpg', 'https://www.youtube.com/watch?v=_odHWsYOm2k', 'Marvel\'s Spider-Man Remastered a été développé par Insomniac Games en collaboration avec Marvel. Vous y incarnez un Peter Parker aguerri combattant le crime contre des ennemis emblématiques dans le New York de Marvel. Il lutte en même temps pour trouver l’équilibre entre sa vie personnelle chaotique et sa carrière tandis que le destin des New-Yorkais est entre ses mains.', NULL),
(10, 2, 'Marvel\'s Spider-Man Miles Morales', '2020-11-12', 'https://img.seriebox.com/jeux/18/18650/jaquette_84_18650_2.png', 'https://www.youtube.com/watch?v=3Ywq3PIKAYo', 'Dans la dernière aventure de l\'univers Marvel’s Spider-Man, le jeune Miles Morales prend ses marques dans son nouveau foyer tout en marchant dans les pas de son mentor, Peter Parker, en tant que nouveau Spider-Man. Mais quand une lutte de pouvoir menace de détruire son nouveau foyer, le héros en devenir se rend compte qu\'un grand pouvoir implique de grandes responsabilités. Pour sauver New York, Mile doit enfiler la tenue de Spider-Man et lui faire honneur.', 85),
(11, 2, 'Marvel\'s Spider-Man 2', '2023-10-20', 'https://img.seriebox.com/jeux/21/21236/jaquette_84_21236_2.jpg', 'https://www.youtube.com/watch?v=9wbmHtyuRZ8', 'Les deux Spider-Man Peter Parker et Miles Morales doivent se dépasser, avec et sans leur masque, alors qu\'ils tentent de sauver à la fois la ville, eux-mêmes et ceux qui leur sont chers du monstrueux Venom et du nouveau danger symbiotique qui les menacent.\r\n\r\nExplorez toute l\'immensité de New York avec des acrobaties aériennes encore plus fluides et une grande nouveauté : les delta-toiles. Passez rapidement de Peter à Miles pour découvrir différentes histoires, de nouvelles capacités épiques ainsi qu\'un équipement à la pointe de la technologie.\r\n\r\nMaîtrisez les capacités symbiotiques de Peter et les pouvoirs bioélectriques explosifs de Miles lors de combats contre les nouveaux super-vilains emblématiques de Marvel. Vous pourrez y découvrir une nouvelle version du symbiote Venom, l\'impitoyable Kraven le Chasseur, l\'instable Lézard, et bien d\'autres encore.', 90),
(12, 2, 'God of War Ragnarök', '2022-11-09', 'https://img.seriebox.com/jeux/19/19166/jaquette_84_19166_3.jpg', 'https://www.youtube.com/watch?v=0taDnGk3oK4&t=6s', 'Rejoignez Kratos et Atreus dans leur voyage légendaire en quête de réponses avant le début du Ragnarök. Ensemble, père et fils devront prendre des risques tout au long de leur périple vers chacun des neuf royaumes.\r\n\r\nAu cœur de paysages mythologiques à couper le souffle, ils affronteront de terribles ennemis, des dieux nordiques aux bêtes sauvages, alors qu\'ils se préparent pour l\'affrontement de leur vie.\r\n\r\nArmé de ses fidèles armes de guerre, et notamment de la Hache Léviathan et des Lames du Chaos, Kratos va voir ses compétences guerrières mises à rude épreuve dans son combat pour protéger sa famille. Atreus et lui auront accès à une myriade de nouvelles capacités, laissant la possibilité à l\'expression et à la fluidité lors des combats de cette épopée épique.\r\n\r\nEt pendant ce temps, Asgard rassemble ses forces...', 94),
(13, 2, 'Horizon Forbidden West', '2022-02-18', 'https://img.seriebox.com/jeux/18/18649/jaquette_84_18649_2.jpg', 'https://www.youtube.com/watch?v=Xk-xq6_Lr6E', 'Rejoignez Aloy tandis qu\'elle s\'aventure dans l\'Ouest prohibé, un territoire dangereux qui abrite de mystérieuses nouvelles menaces.', 88),
(14, 2, ' Ratchet & Clank Rift Apart', '2021-06-11', 'https://img.seriebox.com/jeux/20/20626/jaquette_84_20626_1.jpg', 'https://www.youtube.com/watch?v=rdlsfKt7LS4', 'VIVEZ UNE AVENTURE EXPLOSIVE À TRAVERS LES DIMENSIONS\r\n\r\nRatchet et Clank sont de retour ! Aidez-les à déjouer les plans d\'un empereur robotique déterminé à conquérir toutes les dimensions, y compris celle de nos héros. Découvrez l\'évolution du célèbre duo de choc auquel se joindra Rivet, une Lombax originaire d\'une autre dimension qui résiste à l\'oppresseur.', 88),
(15, 2, 'Demon\'s Souls', '2020-11-12', 'https://img.seriebox.com/jeux/18/18651/jaquette_84_18651_2.jpg', 'https://www.youtube.com/watch?v=JiqGi3GMTko', 'PlayStation Studios et Bluepoint Games proposent un remake du grand classique de la PlayStation, Demon\'s Souls. Recréé de A à Z et bénéficiant de nouveaux graphismes, ce remake permet à une nouvelle génération de joueurs de découvrir cet univers de dark-fantasy brumeux et horrifique. Ceux qui ont déjà affronté ses épreuves périlleuses peuvent replonger dans cet univers sombre, affichant désormais des graphismes stupéfiants et des performances exceptionnelles.\r\n\r\nDans sa quête de puissance, Allant, le 12e roi de Boletaria, a appris à maîtriser les arts de l\'âme antiques, réveillant un démon ancestral, l\'Ancien.\r\nSuite à l\'invocation de l\'Ancien, une brume blafarde s\'est abattue sur le monde, libérant des créatures cauchemardesques cherchant à se repaître d\'âmes humaines. Les êtres dépossédés de leurs âmes par ces créatures sont devenus fous à lier, mus par le seul désir d\'attaquer les esprits sains qui subsistent.\r\n\r\nBoletaria est désormais coupée du monde, et les quelques chevaliers qui osent pénétrer l\'épais brouillard pour tenter de libérer le royaume de son fardeau n\'en ressortent jamais. Guerrier solitaire bravant la brume funeste, vous devez affronter les épreuves les plus insurmontables pour mériter le titre de Fléau des démons et replonger l\'Ancien dans son sommeil éternel.', 92),
(16, 2, 'The Witcher 3 Wild Hunt', '2022-12-14', 'https://img.seriebox.com/jeux/20/20833/jaquette_84_20833_1.jpg', 'https://www.youtube.com/watch?v=N3IuxMLINiw', 'Vous incarnez Geralt de Riv, un mercenaire et tueur de monstres. Devant vous s\'étend un continent infesté de monstres et déchiré par la guerre, que vous pouvez explorer à votre guise. Votre contrat actuel ? Retrouver Ciri, l\'enfant de la prophétie, une arme vivante capable de changer le monde.', NULL),
(17, 3, 'Gears of War 4', '2016-10-11', 'https://img.seriebox.com/jeux/10/10571/jaquette_63_10571_2.jpg', 'https://img.seriebox.com/jeux/11/11397/jaquette_12', 'Un nouveau chapitre s’écrit pour l’une des franchises les plus acclamées de l’histoire du jeu vidéo. Après avoir réchappé de justesse à l’attaque de leur village, JD Fenix et ses amis, Kait et Del, doivent porter secours à leurs proches et découvrir l’origine d’un effroyable nouvel ennemi.', 84),
(18, 3, 'Gears 5', '2018-09-10', 'https://img.seriebox.com/jeux/17/17052/jaquette_63_17052_2.jpg', 'https://www.youtube.com/watch?v=q_Qi14S4Djw', 'Héritier de l\'une des plus grandes sagas du jeu vidéo, Gears revient plus fort que jamais. Alors qu\'une guerre totale est sur le point d\'éclater, Kait Diaz se détache du groupe pour découvrir son lien avec l\'ennemi et comprendre le vrai danger qui plane sur Sera : elle-même.', 84),
(19, 3, 'Forza Motorsport 7', '2017-10-03', 'https://img.seriebox.com/jeux/12/12928/jaquette_63_12928_1.jpg', 'https://www.youtube.com/watch?v=9aAr5blVy0g', 'Ressentez le frisson du sport automobile avec le jeu de course le plus complet, le plus beau et le plus réaliste jamais conçu.\r\n\r\nPilotes, amateurs de drift, fanas de drag, régleurs et créateurs, Forza Motorsport 7 rassemble une communauté entièrement dévouée à l\'automobile. Faites votre choix parmi plus de 700 modèles extraordinaires, dont une collection de Ferrari, Porsche et Lamborghini encore jamais vue, et pilotez les voitures de vos rêves. Lancez-vous sur 30 célèbres circuits et 200 tracés, où les conditions changent à chaque course.', 86),
(20, 3, 'Forza Horizon 4', '2018-10-02', 'https://img.seriebox.com/jeux/14/14590/jaquette_63_14590_1.jpg', 'https://www.youtube.com/watch?v=RCRYs7yfeo4', 'Pour la première fois dans un jeu de course, découvrez des saisons dynamiques dans un monde ouvert partagé. Découvrez de beaux paysages, collectionnez plus de 450 voitures et devenez une Superstar Horizon dans la Grande-Bretagne de l\'époque.', 92),
(21, 3, 'Sea Of Thieves', '2018-03-20', 'https://img.seriebox.com/jeux/13/13430/jaquette_63_13430_1.jpg', 'https://www.youtube.com/watch?v=r5JIBaasuE8', 'Explorez un vaste monde ouvert parsemé d\'îles inexplorées, de navires engloutis et de mystérieux artefacts. Partez à la recherche de trésors perdus, affrontez des capitaines squelettes et protégez les précieuses cargaisons des sociétés. Adonnez-vous à la chasse et à la pêche, et choisissez parmi des centaines d\'objectifs secondaires à remplir !', 69),
(22, 3, 'Halo The Master Chief Collection', '2014-11-13', 'https://www.micromania.fr/dw/image/v2/BCRB_PRD/on/demandware.static/-/Sites-masterCatalog_Micromania/default/dwfd48f647/images/high-res/263216_max.jpg', 'https://www.youtube.com/watch?v=ZDvYJGquXgE', 'Pour la première fois, toute l\'histoire du Master Chief, héros emblématique de Halo, est sur console. La compilation comprends un Halo 2 :  Anniversary remasterisé en plus de Halo : Combat Evolved Anniversary, Halo 3, Halo 4, Halo: Nightfall (une nouvelle série numérique), et l\'accès à la bêta multijoueur de Halo 5 : Guardians. Il s\'agit de l\'expérience Halo suprême!\r\n', 85),
(23, 3, 'Quantum Break', '2016-04-05', 'https://img.seriebox.com/jeux/7/7024/jaquette_63_7024_1.jpg', 'https://www.youtube.com/watch?v=ruY1eT9bXiw', 'Après une fraction de seconde de destruction ayant fracturé l’essence même du temps, deux hommes se rendent compte qu’ils ne sont plus les mêmes et qu’ils possèdent désormais d’extraordinaires pouvoirs. L’un d’entre eux voyage dans le temps et veut à tout prix maîtriser ce don. L’autre tente d\'utiliser ses nouvelles compétences pour l\'en empêcher et faire en sorte que le temps ne soit pas détruit à tout jamais. Tous deux se retrouvent face à un danger incommensurable et devront faire des choix difficiles qui façonneront le futur. Quantum Break est une expérience unique : d’une part jeu vidéo percutant et de l’autre série palpitante portée par un brillant ensemble d\'acteurs. Shawn Ashmore incarne le héros, Jack Joyce, et Aidan Gillen est Paul Serene, son ennemi juré. Dominic Monaghan joue William, le génie et frère de Jack. Quantum Break bénéficie d\'une narration captivante, de personnages hauts en couleur et de rebondissements dramatiques qui ont fait la renommée de Remedy Entertainment. Vos choix influeront sur le dénouement de cette fusion entre jeu vidéo et série qui offrira au joueur une expérience unique et sans précédent.', 77),
(24, 3, 'Recore', '2016-11-16', 'https://m.media-amazon.com/images/I/71MvKbnoMFS._AC_SL1000_.jpg', 'https://www.youtube.com/watch?v=3C96jTk2ss0', 'Vous incarnez Joule Adams, l\'un des derniers humains sur la planète Alter-Éden, un monde mystérieux et dangereux contrôlé par de redoutables robots déterminés à vous éliminer. Pour survivre, vous devrez vous lier d\'amitié avec un courageux groupe de compagnons orbots, chacun doté de capacités et de pouvoirs uniques.', 63),
(25, 4, 'Halo Infinite', '2021-12-08', 'https://m.media-amazon.com/images/I/81hGssseLML._AC_SL1500_.jpg', 'https://www.youtube.com/watch?v=PyMlV5_HRWk', 'Lorsque tout espoir est perdu et que le destin de l’humanité est en jeu, le Master Chief est prêt à affronter l’ennemi le plus impitoyable qu’il ait jamais affronté. Enfile l’armure du plus grand héros de l’humanité pour vivre une aventure épique en monde ouvert et enfin découvrir toute l’étendue de l’anneau de Halo.', 87),
(26, 4, 'Forza Motorsport', '2023-10-10', 'https://img.seriebox.com/jeux/26/26883/jaquette_85_26883_1.jpg', 'https://www.youtube.com/watch?v=em4gv1Ietko', 'Écrasez la concurrence dans un nouveau mode carrière. Affrontez vos amis dans des événements multijoueurs. Pilotez plus de 500 voitures sur des pistes de renommée mondiale en profitant d\'une IA de pointe, d\'une physique avancée et d\'une stratégie de gestion des pneus et du carburant.\r\n', 84),
(27, 4, 'Forza Horizon 5', '2021-11-09', 'https://img.seriebox.com/jeux/21/21182/jaquette_85_21182_3.jpg', 'https://www.youtube.com/watch?v=Rv7xLt5yNsM', 'L’aventure Horizon ultime vous attend ! Explorez les paysages vibrants et changeants du Mexique dans ce jeu en monde ouvert, et amusez-vous sans limite au volant de centaines de voitures phénoménales.', 92),
(28, 4, 'Microsoft Flight Simulator', '2020-08-18', 'https://img.seriebox.com/jeux/20/20965/jaquette_85_20965_2.jpg', 'https://www.youtube.com/watch?v=TYqJALPVn0Y', 'Prends de la hauteur et découvre le plaisir de voler dans la nouvelle génération de Microsoft Flight Simulator. Le monde est à ta portée.', 91),
(29, 4, 'Starfield', '2023-11-06', 'https://img.seriebox.com/jeux/22/22258/jaquette_85_22258_3.jpg', 'https://www.youtube.com/watch?v=Y76r88x-TSI', 'En 2330, l\'humanité s\'est aventurée au-delà de notre système solaire pour s\'établir sur de nouvelles planètes et partir à la découverte de l\'espace. Vous rejoindrez Constellation, le dernier groupe d\'explorateurs de l\'espace à la recherche d\'artéfacts rares à travers la galaxie, et partirez explorer l\'immensité de l\'espace dans le jeu le plus vaste et le plus ambitieux de Bethesda Game Studios à ce jour.', 83),
(30, 4, 'Redfall', '2023-05-02', 'https://m.media-amazon.com/images/I/81yn1oeY87L._AC_SL1500_.jpg', 'https://www.youtube.com/watch?v=KhRC4Qej904', 'Découvrez la vérité, reprenez Redfall\r\nLa ville insulaire de Redfall, dans le Massachusetts, est assiégée par une armée de vampires qui ont occulté le soleil et coupé les habitants du monde extérieur. Explorez ce monde ouvert et plongez-vous dans une campagne à l\'histoire profonde tandis que vous lèverez le voile sur la mystérieuse apparition des vampires. Alliez-vous à une poignée de survivants contre les créatures qui menacent de vider tous les habitants de leur sang.', 56),
(31, 4, 'Palworld', '2024-01-19', 'https://livecards.net/pl/palworld-xbox-one-xbox-series-xs-pc-ar-73682.jpg', 'https://www.youtube.com/watch?v=IltMIJeK-1M&t=1s', 'Un tout nouveau jeu de survie multijoueur en monde ouvert où le but est de collectionner de mystérieuses créatures, les Pals, afin de les faire combattre, bâtir des structures, travailler dans les champs et faire tourner vos usines.', NULL),
(32, 4, 'Age of Empires IV Anniversary Edition', '2023-08-22', 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6562/6562013_sd.jpg;maxHeight=640;maxWidth=550', 'https://www.youtube.com/watch?v=yn4hP2eL0K8', 'Pour célébrer son premier anniversaire, la franchise de jeu de stratégie à succès acclamée par la critique surprend ses millions de joueurs dans le monde avec Age of Empires IV : Édition Anniversaire, qui vous place VOUS au cœur d\'encore plus de batailles épiques qui ont façonnées l\'Histoire.', 83),
(33, 5, 'Astral Chain', '2019-08-30', 'https://img.seriebox.com/jeux/16/16996/jaquette_76_16996_1.jpg', 'https://www.youtube.com/watch?v=sRdTZDVitLY', 'Dans un avenir proche, la Terre est en proie à l\'invasion de créatures venues d\'une autre dimension : les Chimères. Ces monstres répandent la corruption au moyen d\'une substance mystérieuse, la matière rouge, forçant l\'humanité à trouver refuge au sein d\'une mégapole multiculturelle : l\'Arche.', 87),
(34, 5, 'Bayonetta 3', '2022-10-28', 'https://img.seriebox.com/jeux/24/24533/jaquette_76_24533_1.jpg?id=241', 'https://www.youtube.com/watch?v=lr5PrLgFW9o', 'Cette fois le danger ne vient ni de l\'Enfer, ni du Paradis, mais d\'une création de l\'humanité : les homonculus, des armes biologiques qui menacent de détruire la réalité telle qu\'on la connaît.', 86),
(35, 5, 'Kirby et le monde oublié', '2022-03-25', 'https://img.seriebox.com/jeux/21/21412/jaquette_76_21412_1.png?id=81', 'https://www.youtube.com/watch?v=U-RxaJTy5zs', 'Un beau jour, un mystérieux vortex est apparu dans le ciel de la planète Pop, aspirant tout ce qui se trouvait à sa portée... y compris Kirby ! Lorsqu\'il reprend connaissance, notre héros se retrouve dans un nouveau monde, où la nature se mêle aux ruines d\'une civilisation disparue. Il découvre alors que les Waddle Dees ont été capturés par un groupe malveillant qui se fait appeler la meute des bêtes.\r\n\r\nAvec son étrange nouvel ami Elfilin à ses côtés, Kirby se met en quête de sauver tous les Waddle Dees et de retrouver le chemin de sa planète !', 85),
(36, 5, 'Luigi\'s Mansion 3', '2019-10-31', 'https://img.seriebox.com/jeux/16/16762/jaquette_76_16762_3.jpg', 'https://www.youtube.com/watch?v=8tpbDMU9WsM', 'Luigi a été invité à séjourner dans un superbe hôtel avec Mario et ses amis. Comment pourrait-il refuser une telle proposition ? Mais ses rêves de détente vont bientôt se transformer en cauchemar lorsque des fantômes vont se mettre à apparaître et que le Roi Boo va piéger Mario et ses amis dans des tableaux !\r\n\r\nNSwitch_LuigisMansion3_Overview_Resort_Scr_01.png\r\nNSwitch_LuigisMansion3_Overview_Resort_Scr_02.png\r\nGrâce aux gadgets dernier cri de son vieil ami le professeur K. Tastroff, Luigi va devoir une nouvelle fois surmonter ses peurs pour empêcher le Roi Boo d\'agir et sauver ses amis.', 86),
(37, 5, 'Mario Kart 8 Deluxe', '2017-04-28', 'https://img.seriebox.com/jeux/11/11611/jaquette_76_11611_2.jpg', 'https://www.youtube.com/watch?v=tKlRN2YpxRE', 'Que vous fassiez la course en famille, sur grand écran, dans votre salon, au parc ou en visite chez un ami, la Nintendo Switch vous permet de jouer à Mario Kart comme bon vous semble !\r\n\r\nJusqu\'à huit joueurs peuvent se connecter pour une partie en multijoueur local. Si vous jouez en mode téléviseur ou en mode sur table, jusqu\'à quatre joueurs peuvent s\'affronter en écran partagé !\r\n\r\nConnectez-vous à Internet et affrontez des joueurs du monde entier. Jusqu\'à 12 joueurs peuvent prendre part aux courses en ligne. Deux joueurs en local peuvent même jouer en ligne ensemble depuis la même Nintendo Switch !', 92),
(38, 5, 'Metroid Dread', '2021-10-08', 'https://img.seriebox.com/jeux/21/21292/jaquette_76_21292_1.png', 'https://www.youtube.com/watch?v=wQEeHlczPWo', 'Pour mener à bien la mission de Samus, vous devrez explorer les profondeurs d\'une planète tentaculaire pleine d\'environnements uniques, de dangers mortels et de mystérieux secrets. Utilisez tout un panel de capacités, familières comme nouvelles, consultez la carte pour trouver le chemin à suivre et éliminez vos ennemis grâce à votre puissant arsenal.', 88),
(39, 5, 'Pokémon Let\'s Go Pikachu', '2018-11-16', 'https://img.seriebox.com/jeux/13/13864/jaquette_76_13864_1.jpg', 'https://www.youtube.com/watch?v=uPk7Pk52YmI', 'Sac a dos, casquette, Poké Ball... il ne vous manque plus que votre premier Pokémon pour commencer votre aventure sur Nintendo Switch ! Accompagné(e) de Pikachu, incarnez un personnage dont le rêve est de devenir le meilleur dresseur Pokémon et partez découvrir l\'emblématique région de Kanto, inspirée de la version Pokémon Jaune sortie sur Game Boy en 2000 !\r\n\r\nLe système de capture est totalement différent des jeux précédents. Vous pouvez dorénavant lancer une Poké-Ball sur votre cible grâce au Joy-Con de votre Nintendo Switch, en appuyant sur un bouton ou en en donnant un coup de poignet. Moins de boutons, un geste intuitif: il n\'a jamais été aussi simple d\'attraper des Pokémons.\r\n\r\n', 79),
(40, 5, 'Super Mario Odyssey', '2017-10-27', 'https://img.seriebox.com/jeux/12/12666/jaquette_76_12666_1.jpg', 'https://www.youtube.com/watch?v=l0-FNWEnyxQ', 'Bowser a encore enlevé la princesse Peach, et cette fois... Il a prévu d\'organiser un mariage somptueux !\r\n\r\nLe futur marié, qui ne manque pas de piquant, s\'est lancé dans un voyage autour du globe pour préparer les festivités. Mario doit le rattraper pour empêcher ce mariage à tout prix, mais les terribles Broodals ont bien l\'intention de lui compliquer la tâche !', 97),
(41, 5, 'Super Smash Bros Ultimate', '2018-12-07', 'https://img.seriebox.com/jeux/13/13888/jaquette_76_13888_1.jpg', 'https://www.youtube.com/watch?v=cjdfqXIM-Ko', 'Quel jeu de combat réunit plus de 70 personnages jouables, tous issus des univers mythiques du jeu vidéo ? Pour son arrivée sur Nintendo Switch, la saga Super Smash Bros. revient en version ultime. Les règles, elles, restent les mêmes : pour gagner, vous devez éjecter vos adversaires en dehors de l’écran ! Mario, Link, Pikachu, Kirby... les icônes des jeux Nintendo sont de retour pour se bastonner, mais ils ne sont pas seuls. Des invités de marque venus d’autres univers, comme Cloud de la série Final Fantasy ou Snake de Metal Gear Solid répondent aussi à l’appel. Faites votre choix parmi plus de 70 combattants, une multitude de modes de jeu et tentez de devenir le roi de l’arène !', 93),
(42, 5, 'The Legend of Zelda : Tears of the Kingd', '2023-05-12', 'https://img.seriebox.com/jeux/20/20685/jaquette_76_20685_3.jpg', 'https://www.youtube.com/watch?v=Dv-7K_m589I', 'Après The Legend of Zelda : Breath of The Wild, plongez dans des terres d’Hyrule ravagées par les forces obscures dans The Legend of Zelda : Tears of the Kingdom. \r\n\r\nIncarnez le héros de la légende, Link, et décidez du chemin que vous voulez suivre à travers les immenses terres d\'Hyrule et les vastes cieux qui les surplombent. Créez votre propre aventure dans un monde où vous pouvez donner libre cours à votre imagination. Saurez-vous maîtriser la puissance des nouvelles capacités de Link pour lutter contre les forces maléfiques qui menacent le royaume ?', 96),
(43, 6, 'Cyberpunk 2077', '2020-12-10', 'https://img.seriebox.com/jeux/8/8266/jaquette_12_8266_2.jpg', 'https://www.youtube.com/watch?v=BO8lX3hDU30&rco=1', 'Incarnez V, un mercenaire cyberpunk, et faites tout ce qui est en votre pouvoir pour vous faire un nom à Night City : une mégapole où les seules choses qui comptent sont le pouvoir, le glamour et les modifications corporelles. C\'est ici que les légendes s\'écrivent. À quoi ressemblera la vôtre ?', 86),
(44, 6, 'Baldur\'s Gate III', '2023-09-03', 'https://img.seriebox.com/jeux/16/16540/jaquette_12_16540_3.jpg', 'https://www.youtube.com/watch?v=1T22wNvoNiU', 'Constituez votre groupe et retrouvez les Royaumes Oubliés dans cette histoire d\'amitié et de trahison, mais aussi de survie et de sacrifice, sur fond de pouvoir absolu.\r\n\r\nD\'étranges facultés se déclarent en vous depuis que les flagelleurs mentaux vous ont implanté un parasite dans le cerveau. Résistez à ces dons malfaisants et retournez-les contre les forces des ténèbres, ou acceptez la corruption et devenez l\'incarnation du mal.\r\n\r\nUn RPG de nouvelle génération dans l\'univers de Dungeons & Dragons, par les créateurs de Divinity: Original Sin 2.', 96),
(45, 6, 'Diablo IV', '2023-06-06', 'https://img.seriebox.com/jeux/25/25257/jaquette_12_25257_2.jpg', 'https://www.youtube.com/watch?v=XV4zVqb9vWc', 'Découvrez un immense monde ouvert\r\nFrayez-vous un chemin à travers Sanctuaire. Explorez un monde en perpétuelle évolution où se mêlent quêtes, corruption, butin et prises de décisions.\r\n\r\nUne progression de personnage sans limites\r\nCréez votre personnage et personnalisez-le pour affronter les ténèbres. Choisissez votre classe parmi les cinq disponibles et façonnez un protagoniste légendaire unique grâce à une panoplie de talents, de techniques et d’objets ornementaux.\r\n\r\nÉquipement légendaire et batailles épiques\r\nPour vaincre le mal, il faudra vous équiper en conséquence. Profitez d’un riche arsenal d’armes, armures et objets puissants pour lutter contre les hordes démoniaques.', 86),
(46, 6, 'Jurassic World Evolution 2', '2021-11-09', 'https://img.seriebox.com/jeux/20/20649/jaquette_12_20649_2.jpg', 'https://www.youtube.com/watch?v=g76Zx7zydXQ', 'Jurassic World Evolution 2 est la suite très attendue du jeu de gestion immersif, révolutionnaire et hautement acclamé Jurassic World Evolution, édité par Frontier en 2018. Cette suite introduit une nouvelle campagne narrative captivante, d\'incroyables nouvelles fonctionnalités et d\'impressionnants dinosaures inédits, animés avec une authenticité à couper le souffle. Avec de nouveaux bâtiments et plus d\'options de personnalisation, un jeu Jurassic World encore plus vaste, performant et authentique voit le jour.', 76),
(47, 6, 'Farming Simulator 22', '2021-11-22', 'https://img.seriebox.com/jeux/21/21838/jaquette_12_21838_1.jpg', 'https://www.youtube.com/watch?v=JpBzfTe_yWE', 'Entrez dans la peau d\'un agriculteur moderne ! La culture, l\'élevage et la sylviculture offrent un large éventail d\'activités agricoles quand vous affrontez le défi des quatre saisons, en particulier quand l\'hiver s\'installe. Faites preuve de créativité pour bâtir votre propre exploitation et développez vos opérations agricoles avec les chaînes de production pour former un empire agricole ! Vous pouvez même gérer votre exploitation avec des amis en profitant du multijoueur multiplateforme.\r\n\r\nQue vous créiez un vignoble luxuriant ou une oliveraie dans le sud de la France, ou une vaste étendue de blé, de maïs, de coton ou de pomme de terre dans le Midwest des Étas-Unis, ou encore une ferme d\'élevage pittoresque dans le paysage vallonné des Alpes : Plus de 400 machines et outils issus de plus de 100 marques agricoles réelles, comme Case IH, CLAAS, Fendt, John Deere, Massey Ferguson, New Holland, Valtra et bien d\'autres, sont disponibles pour votre exploitation.', 76),
(48, 6, 'Planet Coaster', '2016-11-17', 'https://m.media-amazon.com/images/I/71JV0K9dSzL._AC_SL1000_.jpg', 'https://www.youtube.com/watch?v=91Kli1Uwk9g', 'Surprenez et ravissez vos visiteurs en construisant le parc d\'attractions de vos rêves. Créez et construisez des parcs aux montagnes russes et manèges incroyablement détaillées et gérez des environnements aussi riches que dynamiques.', 84),
(49, 6, 'Alan Wake II', '2023-10-27', 'https://cdn1.epicgames.com/offer/c4763f236d08423eb47b4c3008779c84/EGS_AlanWake2_RemedyEntertainment_S2_1200x1600-c7c8091ddac0f9669c8e5905bca88aaa', 'https://www.youtube.com/watch?v=MEWgOlTIW4Y', 'Alan Wake, écrivain de polars à succès vivant à New York, a disparu en 2010. Lors de vacances sur la côte nord-ouest du Pacifique en compagnie de sa femme Alice, Alan a été confronté à une ténébreuse force surnaturelle. Celle-ci a transformé le récit horrifique de l’écrivain en réalité. Alan a affronté l’Ombre Noire et réussi à la renvoyer d’où elle venait, un antre noir cauchemardesque caché sous un lac de cratère bordant la petite ville de Bright Falls. Wake a écrit une fin à son récit d’horreur, ce qui lui a permis de libérer sa femme des ténèbres sous le lac avant de devenir lui-même prisonnier de ce lieu.', 89),
(50, 6, 'Counter-Strike 2', '2023-09-28', 'https://upload.wikimedia.org/wikipedia/en/f/f2/CS2_Cover_Art.jpg', 'https://www.youtube.com/watch?v=c80dVYcL69E', 'Counter-Strike, c\'est l\'expérience compétitive par excellence qui réunit des millions de personnes depuis plus de vingt ans. L\'heure est venue d\'écrire le prochain chapitre de l\'histoire de Counter-Strike. Faites place à Counter-Strike 2.\r\n\r\nAvec Counter-Strike 2, l\'amélioration gratuite de CS:GO, Counter-Strike effectue le plus grand bond technique de toute son histoire. Grâce au moteur Source 2, Counter-Strike 2 bénéficie d\'un rendu physique réaliste, d\'une architecture de réseau à la pointe et de nouveaux outils du Workshop pour la communauté.', 82),
(51, 6, 'Hogwarts Legacy : L\'Héritage de Poudlard', '2023-02-10', 'https://img.seriebox.com/jeux/19/19081/jaquette_12_19081_1.jpg?id=864', 'https://www.youtube.com/watch?v=BtyBjOW8sGY', 'Hogwarts Legacy : L\'Héritage de Poudlard est un RPG d\'action-aventure immersif en monde ouvert qui se déroule dans l’univers des livres Harry Potter. Pour la première fois, découvrez Poudlard dans les années 1800. Vous incarnez une élève détenant la clé d\'un ancien secret qui menace de déchirer le monde des sorciers. Vous pouvez maintenant prendre le contrôle de l\'action et être au centre de votre propre aventure dans le monde des sorciers. Votre héritage vous appartient.', 83),
(52, 6, 'Sons of the Forest', '2023-02-23', 'https://img.seriebox.com/jeux/25/25149/jaquette_12_25149_1.gif', 'https://www.youtube.com/watch?v=8sghWJKPWno', 'En mission sur une île isolée pour retrouver un milliardaire porté disparu, vous découvrez un monde de cauchemar infesté de cannibales. Par vous-même ou avec l\'aide d\'amis, fabriquez, construisez et luttez pour votre survie dans ce jeu de simulation de survie horrifique.', 86);

-- --------------------------------------------------------

--
-- Structure de la table `plateforme`
--

CREATE TABLE `plateforme` (
  `id_plateforme` int(11) NOT NULL,
  `nom` varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `plateforme`
--

INSERT INTO `plateforme` (`id_plateforme`, `nom`) VALUES
(1, 'PS4'),
(2, 'PS5'),
(3, 'XBOX ONE'),
(4, 'SERIES S/X'),
(5, 'SWITCH'),
(6, 'PC');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `jeux`
--
ALTER TABLE `jeux`
  ADD PRIMARY KEY (`id_jeux`);

--
-- Index pour la table `plateforme`
--
ALTER TABLE `plateforme`
  ADD PRIMARY KEY (`id_plateforme`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `jeux`
--
ALTER TABLE `jeux`
  MODIFY `id_jeux` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT pour la table `plateforme`
--
ALTER TABLE `plateforme`
  MODIFY `id_plateforme` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
